name: Deploy to EC2

on:
  push:
    branches:
      - main  # Deploy to production on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Debug EC2_KEY
        run: echo "EC2_KEY content: ${{ secrets.EC2_KEY }}"
