name: Deploy to EC2

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Prepare SSH key
        run: echo "${{ secrets.EC2_KEY }}" | base64 -d > /home/runner/.ssh/id_rsa
        shell: bash

      - name: Set SSH key permissions
        run: chmod 600 /home/runner/.ssh/id_rsa
        shell: bash

      - name: Add SSH key to the agent
        run: eval $(ssh-agent) && ssh-add /home/runner/.ssh/id_rsa
        shell: bash

      - name: Add SSH known hosts
        run: ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /path/to/your-app
            git pull
            npm install
            npm run build
            pm2 restart next-app
          EOF
        shell: bash
